# Generated by Django 5.1.2 on 2024-10-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogdan_3_app', '0002_group_profile_remove_book_author_remove_genre_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comments', to='bogdan_3_app.user', verbose_name='Автор'),
        ),
    ]
