# Generated by Django 5.1.2 on 2024-10-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogdan_3_app', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='group_users', to='bogdan_3_app.user', verbose_name='Участники'),
        ),
    ]
