# Generated by Django 5.1.2 on 2024-10-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogdan_3_app', '0004_alter_group_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования'),
        ),
    ]
